server:
  port: 8469
logging:
  file: /java/C2S_LOGS/iexhub-xdsb/iexhub-xdsb.log
info:
  component: IExHub XDS.b Spring Boot
ribbon:
  ReadTimeout: 50000
hystrix.command.default.execution.timeout.enabled: false
c2s:
  iexhub-xdsb:
    hieos:
      enabled: true
      # configure HIEOS specific information
      xdsBRegistryEndpointURI: http://bhitsdevhie01:9080/axis2/services/xdsregistryb
      xdsBRepositoryEndpointURI: http://bhitsdevhie01:9080/axis2/services/xdsrepositoryb
      xdsBRepositoryUniqueId: 1.3.6.1.4.1.21367.13.40.216
      documentsOutputPath: /java/C2S_LOGS/iexhub-xdsb/documents
      clientSocketTimeoutInMs: 768000
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /iexhub-xdsb