server:
  port: 8469
logging:
  file: /java/C2S_LOGS/iexhub-xdsb/iexhub-xdsb.log
info:
  component: IExHub XDS.b Spring Boot
ribbon:
  ReadTimeout: 50000
hystrix.command.default.execution.timeout.enabled: false
c2s:
  iexhub-xdsb:
    hieos:
      enabled: true
      # configure HIEOS specific information
      xdsbRegistryEndpointURI: http://bhitsdevhie01:9080/axis2/services/xdsregistryb
      xdsbRepositoryEndpointURI: http://bhitsdevhie01:9080/axis2/services/xdsrepositoryb
      xdsbRepositoryUniqueId: 1.3.6.1.4.1.21367.2010.1.2.1040
      openEmpiDomainId: 2.16.840.1.113883.4.357
      clientSocketTimeoutInMs: 768000
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /iexhub-xdsb